#ifndef __MPCONFIG_BOARD_H
#define __MPCONFIG_BOARD_H

#define MICROPY_HW_BOARD_NAME "MicroMINT Bambino210E"
#define MICROPY_HW_MCU_NAME "LPC4337"

#define MICROPY_HW_UART_REPL        PYB_UART_2
#define MICROPY_HW_UART_REPL_BAUD   115200

#endif /* __MPCONFIG_BOARD_H */
